<?php

namespace Tests\ModelsTest;

use App\Models\OAuthClient;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class OAuthClientTest extends TestCase
{
    use DatabaseTransactions;

    public function testGenerateSecureClientId()
    {
        $id = OAuthClient::generateSecureClientId();

        $this->assertIsString($id);
        $this->assertEquals(36, strlen($id));
    }

    public function testGenerateSecureClientIdUniqueness()
    {
        $ids = [];

        for ($i = 0; $i < 100; $i++) {
            $id = OAuthClient::generateSecureClientId();
            $this->assertNotContains($id, $ids, 'Generated ID should be unique');
            $ids[] = $id;
        }
    }

    public function testClientIdFormat()
    {
        $id = OAuthClient::generateSecureClientId();

        $this->assertMatchesRegularExpression('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i', $id);
    }

    public function testClientModelUsesNonIncrementingKey()
    {
        $client = new OAuthClient();

        $this->assertFalse($client->getIncrementing());
        $this->assertEquals('string', $client->getKeyType());
    }

    public function testClientCreationWithAutoGeneratedId()
    {
        $client = OAuthClient::create([
            'user_id' => 1,
            'name' => 'Test Client',
            'secret' => 'test-secret',
            'redirect' => 'http://localhost/callback',
            'personal_access_client' => false,
            'password_client' => false,
            'revoked' => false,
        ]);

        $this->assertNotNull($client->id);
        $this->assertEquals(36, strlen($client->id));
        $this->assertMatchesRegularExpression('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i', $client->id);
    }

    public function testMultipleClientsHaveDifferentIds()
    {
        $client1 = OAuthClient::create([
            'user_id' => 1,
            'name' => 'Test Client 1',
            'secret' => 'secret1',
            'redirect' => 'http://localhost/callback',
            'personal_access_client' => false,
            'password_client' => false,
            'revoked' => false,
        ]);

        $client2 = OAuthClient::create([
            'user_id' => 1,
            'name' => 'Test Client 2',
            'secret' => 'secret2',
            'redirect' => 'http://localhost/callback',
            'personal_access_client' => false,
            'password_client' => false,
            'revoked' => false,
        ]);

        $this->assertNotEquals($client1->id, $client2->id);
    }
}
