name: Release

on:
  push:
    branches:
      - dev
  watch:
    types: started
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build and create archive
      run: ./tools/release.ps1
      shell: pwsh

# 设置 AWS 凭证
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        # 设置 AWS 凭证过期时间，默认为 1 小时
        expires-in: 3600

    # 将目录上传到 S3
    - name: Sync to S3
      run: |
        aws s3 cp ./qiniu/server s3://${{ secrets.AWS_S3_Name }}/server --recursive

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: blessing-skin-server
        path: ./blessing-skin-server-*.zip
