name: Release

on:
  push:
    branches:
      - dev
  watch:
    types: started
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        coverage: none
        extensions: mbstring, dom, fileinfo, sqlite, gd, zip

    - name: Build and create archive
      run: ./tools/release.ps1
      shell: pwsh
    - name: Upload qiniu
      run: |
        wget https://devtools.qiniu.com/qshell-v2.9.0-linux-386.tar.gz?ref=developer.qiniu.com -O qshell.tar.gz
        tar -zxvf qshell.tar.gz
        ./qshell account ${{ secrets.QINIU_AccessKey }} ${{ secrets.QINIU_SecretKey }} bs
        ./qshell qupload2 --src-dir=./dist --bucket=${{ secrets.QINIU_Name }} --overwrite=true --rescan-local=true --check-hash=true
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: blessing-skin-server
        path: ./blessing-skin-server-*.zip
